### ISSUE TITLE
reduce computation at is_colided.c

### ISSUE THREAD

**Issue by tyamagis** [velvelhype/term3d#25]
is_colided.c at line 43, 44
> sin(i->deg), cos(i->deg)
> they could be const at each loop.

**Comment by tyamagis** [comment]
calc_data() (in loop_draw.c) is good to calc sin() and cos().
Before entering while loop, calculate sin() and cos() then assign them to t_term->member.

**Comment by tyamagis** [comment]
Save converted vertexes, we can reduce sin() and cos() computing. 
 - Rotate speed is constant (= increase degree is constant), then sin(deg) and cos(deg) may be constant. 
 - We can define increase degree at header file.

**Comment by velvelhype** [comment]
done!
